server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  api-docs:
    path: /v3/api-docs

spring:

  application:
    name: "Gestion De Reservas"

  profiles:
    active: local  # o 'prod' para producción
  jpa:
    hibernate:
      ddl-auto: update