server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
  api-docs:
    path: /api-docs

spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: luxehavenh@gmail.com
    password: oniw aqkl rjyr sndq
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  application:
    name: "Gestion De Reservas"

  profiles:
    active: local  # o 'prod' para producción
  jpa:
    hibernate:
      ddl-auto: update